export const REQ_START="REQ_START"
export const REQ_FAIL="REQ_FAIL"
export const GET_ALL_RECORDS="GET_ALL"
export const GET_BY_CODE="GET_BY_CODE"
export const REQ_ADD="REQ_ADD"
export const REQ_UPDATE="REQ_UPDATE"
export const REQ_DELETE="REQ_DELETE"
export const OPEN_POPUP="OPEN_POPUP"